metaopt/optree

- README.md
- docs/source/spelling_wordlist.txt
- include/registry.h
- include/treespec.h
- include/utils.h
- optree/_C.pyi
- optree/__init__.py
- optree/ops.py
- optree/registry.py
- optree/typing.py
- src/optree.cpp
- src/registry.cpp
- src/treespec/flatten.cpp
- src/treespec/traversal.cpp
- src/treespec/treespec.cpp
- src/treespec/unflatten.cpp
- tests/helpers.py
- tests/test_ops.py
- tests/test_registry.py
- tests/test_treespec.py
Add namespace isolation for custom node type registry.
> feat(ops): namespace support for custom node type registry

- CMakeLists.txt
- README.md
- include/registry.h
- include/treespec.h
- include/utils.h
- setup.py
- src/registry.cpp
- src/treespec/flatten.cpp
- src/treespec/traversal.cpp
- src/treespec/treespec.cpp
- src/treespec/unflatten.cpp
- tests/test_ops.py
> feat: better internal error handling

- include/treespec.h
Signed-off-by: Aaron Gokaslan <aaronGokaslan@gmail.com>
* Remove a move that doesn't do anything found via clang-tidy (data_hash is an ssize_t).
> style: remove useless move found via clang-tidy

- .pre-commit-config.yaml
Add `clang-format` to pre-commit hooks.
Resolves https://github.com/metaopt/optree/pull/19#issuecomment-1400540219
> feat(pre-commit): add `clang-format` hook

- docs/source/typing.rst
- include/utils.h
- optree/__init__.py
- optree/registry.py
- optree/typing.py
- pyproject.toml
- src/registry.cpp
- tests/test_registry.py
Raise a `UserWarning` when registering subclasses of `namedtuple`. All subclasses of `namedtuple` are already registered. Users can override it with custom flatten/unflatten functions. We raise a warning here for the notice.
> feat(registry): raise a warning when registering subclasses of namedtuple

- .github/workflows/build.yml
- pyproject.toml
Add pre-build wheel for Linux aarch64 ~and ppc64le/s390x~ and Windows arm64.
> feat: build Linux AArch64 and Windows ARM64 wheels (#25

- .flake8
- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- include/utils.h
- optree/__init__.py
- optree/ops.py
- pyproject.toml
- src/treespec/flatten.cpp
- src/treespec/treespec.cpp
- src/treespec/unflatten.cpp
- tests/test_ops.py
- tests/test_typing.py
> style: make error message more clear when value mismatch

- CHANGELOG.md
- include/utils.h
- src/treespec/flatten.cpp
- tests/test_prefix_errors.py
Replace the sort-based comparison with `PyDict_Contains` in for-loops. This will reduce the time complexity for `dict` keys equality test from $O (n \log n)$ to $O (n)$.
> perf(flatten_up_to): test dict key equality with `PyDict_Contains`

- .pre-commit-config.yaml
- CHANGELOG.md
- optree/ops.py
- optree/typing.py
The argument in `tree_reduce`  was changed from `initial` to `initializer` in #39. I realized this is a documentation issue in Python. The signature in Python C code is `initial`. This PR reverts the changes for the argument name in `tree_reduce`.
Ref:
- python/cpython#102757
- python/cpython#102759
- python/cpython#102757
- python/cpython#102759
If you are unsure about any of these, don't hesitate to ask. We …
> fix(ops): align kwargs for `tree_reduce` with `functools.reduce` with the Python C implementation

- CHANGELOG.md
- optree/typing.py
Add `@runtime_checkable` decorator for `CustomTreeNode` protocol class.
Fix CI failure since `typing-extensions` 4.6.0 was released.
Refs:
- python/typing_extensions#161
- python/cpython#26067
- python/typing_extensions#132
- python/typing_extensions#134
- python/typing_extensions#178
> fix(typing): add `@runtime_checkable` decorator for `CustomTreeNode` protocol class

- CHANGELOG.md
- src/treespec/flatten.cpp
- tests/test_ops.py
This PR adds the missing procedure to add the current path into the `paths` result.
The process is the same as the switch case for `PyTreeKind::Leaf`.
https://github.com/metaopt/optree/blob/d1e85f8975f132968e23fa70406d7353adb84155/src/treespec/flatten.cpp#L234-L242
Fixes #75.
> fix(ops): fix empty paths when flatten with custom `is_leaf` function

- .github/workflows/tests.yml
- CHANGELOG.md
- CMakeLists.txt
- pyproject.toml
- tests/test_ops.py
- bump pybind11 version to 2.11.1
- add initial Python 3.12 support
> deps(pybind11): bump pybind11 version to 2.11.1 and add initial Python 3.12 support

- .pre-commit-config.yaml
- CHANGELOG.md
- include/treespec.h
- include/utils.h
- src/CMakeLists.txt
- src/treespec/treespec.cpp
- tests/test_treespec.py
Add a set to memorize ongoing `repr` / `hash` calls to resolve infinite recursion under self-referential case.
Fixes #81
> fix(treespec): memorize ongoing `repr` / `hash` calls to resolve infinite recursion under self-referential case

- .clang-tidy
- CHANGELOG.md
- CMakeLists.txt
- include/exceptions.h
- include/registry.h
- include/treespec.h
- include/utils.h
- src/CMakeLists.txt
- src/optree.cpp
- src/registry.cpp
- src/treespec/flatten.cpp
- src/treespec/treespec.cpp
- src/treespec/unflatten.cpp
> refactor: remove dependence on `abseil-cpp`

- .github/workflows/build.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- include/utils.h
- pyproject.toml
- src/treespec/treespec.cpp
> deps(python): enable Python 3.12 support

- .pre-commit-config.yaml
- CHANGELOG.md
- include/treespec.h
- optree/__init__.py
- optree/ops.py
> chore: set recursion limit to 2000 for all platforms

- CHANGELOG.md
- docs/source/spelling_wordlist.txt
- include/utils.h
- optree/typing.py
- src/optree.cpp
- tests/test_typing.py
Use `cls.__bases__ == (tuple,)` rather than `cls.__base__ is tuple` to check the direct inheritance from `tuple`.
See also https://github.com/pytorch/pytorch/pull/113258#discussion_r1386931064
> refactor(typing): use `__bases__` rather than `__base__` in function `is_structseq_class`

- .pre-commit-config.yaml
- CHANGELOG.md
- docs/source/spelling_wordlist.txt
- include/utils.h
- optree/typing.py
- tests/test_typing.py
> feat(typing): also check `_make` and `_asdict` in function `is_namedtuple_class`

- include/utils.h
- optree/typing.py
- src/optree.cpp
Intern cached string literals to speed up Python internal dictionary lookup.
> perf: intern cached `str` objects

- .pre-commit-config.yaml
- CHANGELOG.md
- include/utils.h
- optree/ops.py
- optree/registry.py
- src/registry.cpp
- src/treespec/treespec.cpp
- tests/test_ops.py
Move the `PyStructSequence` check before the `namedtuple` check.
The `PyStructSequence` types will be more similar to the `namedtuple` types in the future. It's hard to distinguish these two types if the `PyStructSequence` types will have `_fields` attributes.
- pytorch/pytorch#113258
- python/cpython#46145
- python/cpython#108648
This PR moves the `PyStructSequence` type check before the `namedtuple` type check.
> refactor: reorder cases for `namedtuple` and `PyStructSequence` types

- .pre-commit-config.yaml
- CHANGELOG.md
- include/registry.h
- include/treespec.h
- include/utils.h
- src/registry.cpp
- src/treespec/flatten.cpp
- src/treespec/traversal.cpp
- src/treespec/treespec.cpp
- src/treespec/unflatten.cpp
- Use `py::object` in public methods.
- Use `py::handle` in implementation details.
> refactor: standardize `py::handle` and `py::object` usage in function signature

- CHANGELOG.md
- include/treespec.h
- src/treespec/flatten.cpp
- src/treespec/treespec.cpp
- tests/test_treespec.py
Always make a copy of the dict key list. This fixes a potential segmentation fault when users modify `treespec.entries()`.
```python
In [1]: import optree
In [2]: spec = optree.tree_structure({'a': 1, 'b': 2})
In [3]: spec
Out[3]: PyTreeSpec({'a': *, 'b': *})
In [4]: spec.entries().clear()
In [5]: optree.tree_unflatten(spec, range(spec.num_leaves))
[1]    39564 segmentation fault  ipython
```
If you are unsure …
> fix(treespec): fix potential segmentation fault when modifying `treespec.entries()`

- .clang-tidy
- include/registry.h
- src/treespec/flatten.cpp
> lint: appease clang-tidy warnings

- CHANGELOG.md
- docs/source/registry.rst
- include/registry.h
- include/treespec.h
- optree/_C.pyi
- optree/__init__.py
- optree/registry.py
- src/optree.cpp
- src/registry.cpp
- src/treespec/constructor.cpp
- src/treespec/flatten.cpp
- src/treespec/treespec.cpp
- tests/helpers.py
- tests/test_registry.py
- tests/test_treespec.py
- Change the registration pointer in the `PyTreeSpec` object from raw pointer to shared pointer.
- Add API to unregister node type in the registry.
```python
optree.register_pytree_node(
set,
lambda s: (sorted(s), None, None),
lambda _, children: set(children),
namespace='set',
)
optree.unregister_pytree_node(set, namespace='set')
```
Resolves #119
If you are unsure about any of these, don't hesitate to ask. We …
> feat(registry): add API to unregister node type in the registry

- .github/workflows/build.yml
- CHANGELOG.md
- Makefile
- docs/source/ops.rst
- include/treespec.h
- optree/_C.pyi
- optree/__init__.py
- optree/registry.py
- optree/typing.py
- pyproject.toml
- src/optree.cpp
- src/treespec/constructor.cpp
- src/treespec/flatten.cpp
- src/treespec/traversal.cpp
- tests/helpers.py
- tests/test_functools.py
- tests/test_ops.py
- tests/test_prefix_errors.py
- tests/test_registry.py
- tests/test_treespec.py
> feat(registry): add context manager to temporarily set the dictionary sorting mode

- CHANGELOG.md
- Makefile
- optree/registry.py
- pyproject.toml
- tests/test_ops.py
Move global warning filters into a `warnings.catch_warnings()` context.
Resolves #148
> fix: fix warning regression during import when launch with strict warning filters

- CHANGELOG.md
- CMakeLists.txt
- Makefile
- conda-recipe.yaml
- docs/conda-recipe.yaml
- docs/requirements.txt
- pyproject.toml
- setup.py
Use `Python` instead of `PYTHON` in cmake files.
> refactor(cmake): use `cmake`'s `FindPython` module

- CHANGELOG.md
- optree/dataclasses.py
- optree/registry.py
- optree/typing.py
- tests/.coveragerc
- tests/test_typing.py
Add a wrapped version that has attributes `__cxx_implementation__` and `__python_implementation__` can be accessible.
Expose Python implementation for PyTorch Dynamo support.
> feat(typing): expose Python implementation for C utilities for `namedtuple` and `PyStructSequence`

- optree/dataclasses.py
- pyproject.toml
Two minor fixes in dataclasses.py
- Type annotations for the `field` function have to "lie" to the typechecker to be useful in the context of declaring a dataclass. The current change copies what is used for the standard library `dataclasses.field`. (I used [this](https://github.com/python/typeshed/blob/main/stdlib/dataclasses.pyi) as a reference.)
- The spec says `@dataclass_transform` should only be used on a single overload. (See second paragraph [here](https://typing.readthedocs.io/en/latest/spec/dataclasses.html#dataclass-transform).)
This was already discussed in [163](https://github.com/metaopt/optree/issues/163).
If …
> lint(dataclasses): improve annotation for `optree.dataclasses.field()`

- CHANGELOG.md
- README.md
- pyproject.toml
- setup.py
Add the dependency on PyPI `cmake` package only when the system tool is not available, and use it otherwise.
This avoids an unnecessary dependency on a third-party binary package, and improves portability by letting users benefit from downstream patching.
close #187 
> feat(setup): support using system CMake

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/set_release.py
- .github/workflows/tests-with-pydebug.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- Makefile
- README.md
- optree/registry.py
- pyproject.toml
- setup.py
- tests/test_registry.py
Unset `PYTHONPATH` before calling `cmake` in subprocess.
See the following issues for more context:
- #187
- #188
- scikit-build/cmake-python-distributions#586
- pypa/pip#13222
> fix(setup): fix a cannot found `cmake` issue when install from source with venv'ed `cmake`

- .github/workflows/tests-with-pydebug.yml
- .github/workflows/tests.yml
- setup.py
A follow up fix for another environment setting after #191.
- #191
> fix(setup): fix a cannot found `cmake` issue when install from source without system `cmake`

- CHANGELOG.md
- docs/source/api.rst
- optree/__init__.py
- optree/registry.py
- pyproject.toml
- tests/test_prefix_errors.py
- tests/test_registry.py
> chore!(registry): remove deprecated key path APIs

- tests/helpers.py
- tests/test_treespec.py
> fix(tests): prepend `tests/` to `PYTHONPATH` in subprocess call in tests

- setup.py
Convert the pathlib.Path instance to a string when passing to `mkpath`
Otherwise it may error with
> mkpath: 'name' must be a string (got PosixPath
The actual implementation of the extension class varies depending on what packages are installed, so it does not error in all environments. 
> chore(setup): pass `build_temp` as string to `mkpath`

- CHANGELOG.md
- optree/dataclasses.py
- tests/test_dataclasses.py
Do not fail if users pass `namespace=''` to `optree.dataclasses.{,make_}dataclass`.
Resolve #210
> feat(dataclasses): allow creating dataclass types in the global namespace

- CHANGELOG.md
- include/optree/treespec.h
- src/optree.cpp
- src/treespec/gc.cpp
- tests/test_treespec.py
> feat: implement optional `tp_clear` for class `PyTreeSpec` and `PyTreeIter`

- .pre-commit-config.yaml
- docs/source/pytree.rst
- docs/source/spelling_wordlist.txt
- optree/__init__.py
- optree/pytree.py
- pyproject.toml
- tests/test_shortcut.py
> feat(pytree): add re-export API `optree.pytree.reexport(...)`

- CHANGELOG.md
- include/optree/treespec.h
- src/optree.cpp
Related:
- pybind/pybind11#5708
> fix: handle  `pybind11` macro defined as 0 instead of non-exist
