metaopt/optree

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/questions_help_support.md, .github/PULL_REQUEST_TEMPLATE.md
add github templates for better issue and pr management
=> chore(.github): add github templates

Makefile, docs/source/spelling_wordlist.txt, optree/__init__.py, optree/typing.py, optree/version.py, tests/.coveragerc
=> feat(typing): better type annotation for type alias

include/utils.h
References:
- #13
- #14
- https://github.com/pybind/pybind11/issues/4263#issuecomment-1327110684
- https://github.com/pybind/pybind11/issues/4263#issuecomment-1327470506
- https://github.com/pybind/pybind11/issues/4263#issuecomment-1327510732
=> refactor: use static raw pointers for global imports

.github/workflows/lint.yml, .pre-commit-config.yaml, CONTRIBUTING.md, Makefile, conda-recipe.yaml, docs/conda-recipe.yaml, docs/source/spelling_wordlist.txt, optree/ops.py, optree/registry.py, optree/typing.py, pyproject.toml, tests/requirements.txt
Add `xdoctest` integration and update examples accordingly.
=> feat: add `doctest` integration

src/treespec/treespec.cpp
=> fix(treespec): fix C++-17 compatibility

include/exceptions.h, include/treespec.h, include/utils.h, src/registry.cpp, src/treespec/flatten.cpp, src/treespec/traversal.cpp, src/treespec/treespec.cpp, src/treespec/unflatten.cpp
=> style: always explicitly initialize C++ objects

.pre-commit-config.yaml, optree/registry.py, optree/utils.py, tests/test_prefix_errors.py
=> style: miscellaneous style housekeeping

CHANGELOG.md, optree/version.py
=> ver: bump version to 0.10.0

.clang-tidy, .github/workflows/lint.yml, CHANGELOG.md, Makefile, include/exceptions.h, include/registry.h, include/treespec.h, include/utils.h, src/optree.cpp, src/registry.cpp, src/treespec/flatten.cpp, src/treespec/traversal.cpp, src/treespec/treespec.cpp, src/treespec/unflatten.cpp
=> feat(Makefile): install `clang-format` and `clang-tidy` from PyPI

CHANGELOG.md, optree/integration/jax.py, optree/integration/numpy.py, optree/integration/torch.py, optree/utils.py, optree/version.py
=> ver: bump version to 0.11.0

.github/workflows/build.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, CHANGELOG.md, CMakeLists.txt, benchmark.py, include/treespec.h, optree/integration/jax.py, optree/registry.py, setup.py, tests/helpers.py, tests/test_ops.py, tests/test_prefix_errors.py, tests/test_treespec.py, tests/test_utils.py
=> refactor(setup.py): refactor build system

.github/workflows/build.yml, CHANGELOG.md
=> feat(workflows): add Linux ppc64le and s390x wheels

.github/workflows/build.yml, CHANGELOG.md, CMakeLists.txt, include/treespec.h, include/utils.h, pyproject.toml, setup.py, src/treespec/constructor.cpp, src/treespec/flatten.cpp, src/treespec/traversal.cpp, src/treespec/treespec.cpp
=> feat: support 32-bit builds

.github/workflows/build.yml, .github/workflows/tests.yml, CHANGELOG.md, Makefile, optree/version.py, pyproject.toml, src/registry.cpp, src/treespec/constructor.cpp, src/treespec/flatten.cpp, src/treespec/traversal.cpp, src/treespec/treespec.cpp, tests/requirements.txt, tests/test_treespec.py
=> fix(treespec): fix potential segmentation fault for pickling support

.pre-commit-config.yaml, CHANGELOG.md, include/registry.h, include/treespec.h, include/utils.h, optree/integration/jax.py, optree/integration/numpy.py, optree/integration/torch.py, src/optree.cpp, src/registry.cpp, src/treespec/constructor.cpp, src/treespec/flatten.cpp, src/treespec/treespec.cpp, tests/helpers.py, tests/integration/test_jax.py, tests/integration/test_numpy.py, tests/integration/test_torch.py, tests/test_registry.py, tests/test_treespec.py, tests/test_typing.py
=> fix(treespec): fix gc for self-referential case by implementing `tp_traverse`

.github/workflows/build.yml, .github/workflows/set_cibw_build.py, .github/workflows/tests.yml, CHANGELOG.md, include/treespec.h, include/utils.h, optree/typing.py, pyproject.toml, src/treespec/treespec.cpp, tests/helpers.py, tests/test_ops.py, tests/test_registry.py, tests/test_treespec.py, tests/test_typing.py
=> feat: add PyPy support

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, CHANGELOG.md, CMakeLists.txt, include/exceptions.h, include/registry.h, include/utils.h, src/optree.cpp, src/registry.cpp, tests/test_treespec.py
=> feat(workflows): add tests with PyDebug enabled in CI

.github/workflows/build.yml, .github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, CHANGELOG.md, optree/integration/__init__.py, optree/typing.py, pyproject.toml
=> deps(python): enable Python 3.13 support

CHANGELOG.md, docs/source/spelling_wordlist.txt, optree/ops.py, optree/registry.py, optree/typing.py
=> chore(typing): improve typing support for generic `PyTree[T]` and registry lookup / register functions

.pre-commit-config.yaml, optree/dataclasses.py, optree/ops.py
=> lint(dataclasses): fix annotation for `@optree.dataclasses.dataclass`

CHANGELOG.md, README.md, docs/source/spelling_wordlist.txt, optree/accessor.py, optree/dataclasses.py, optree/functools.py, optree/ops.py, optree/registry.py, optree/typing.py, tests/helpers.py, tests/test_accessor.py, tests/test_ops.py
=> feat(ops): add more info to `tree_flatten_one_level`

.github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, .gitignore, .pre-commit-config.yaml, CHANGELOG.md, Makefile, include/optree/treespec.h, src/treespec/treespec.cpp, src/treespec/unflatten.cpp, tests/test_treespec.py
=> feat(workflows): upload core dump files in workflows

.pre-commit-config.yaml, CHANGELOG.md, CMakeLists.txt, setup.py, src/CMakeLists.txt
=> fix(setup): fix cross-compiling for ARM64 on x64 Windows

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, CHANGELOG.md, Makefile, pyproject.toml
=> chore!(setup): enable CXX11 ABI in C++ extension

.github/workflows/lint.yml, .github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, CHANGELOG.md, Makefile, README.md, docs/source/pytree.rst, docs/source/spelling_wordlist.txt, docs/source/treespec.rst, optree/ops.py, optree/registry.py, tests/test_registry.py
=> feat(registry): support lookup all registry entries in a `namespace`

.github/workflows/build.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, CHANGELOG.md
=> chore(workflows/build): enable PyPy 3.11 support

CHANGELOG.md, CMakeLists.txt, include/optree/treespec.h, optree/_C.pyi, src/optree.cpp, src/treespec/traversal.cpp, tests/test_ops.py, tests/test_registry.py
=> feat(treespec): add method `PyTreeSpec.traverse`

.github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, CHANGELOG.md, MANIFEST.in, Makefile
=> chore(MANIFEST.in): include test suites in SDist

.github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, CHANGELOG.md, MANIFEST.in, Makefile, conda-recipe.yaml, docs/source/api.rst, docs/source/spelling_wordlist.txt, optree/dataclasses.py, optree/integration/__init__.py, optree/integration/jax.py, optree/integration/numpy.py, optree/integration/torch.py, optree/registry.py, optree/typing.py, pyproject.toml, tests/.coveragerc, tests/confcoverage.py, tests/requirements.txt, tests/test_ops.py, tests/test_prefix_errors.py, tests/test_treespec.py
=> feat(tests): include branch coverage and add conditional pragmas

.github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, CHANGELOG.md, optree/registry.py, setup.py
=> feat(setup): detect `cmake` version and guard minimum version

.github/workflows/tests.yml
=> chore(workflows/tests): add Python 3.13t to test matrix

.github/workflows/tests.yml, CHANGELOG.md, Makefile, tests/helpers.py, tests/test_concurrent.py, tests/test_treespec.py
See also:
- https://github.com/conda-forge/optree-feedstock/pull/35#issuecomment-2781693343
=> test: explicitly set recursion limit for recursion tests

.github/workflows/build.yml, .github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, CHANGELOG.md, README.md, benchmark.py, include/optree/pymacros.h, optree/accessor.py, optree/dataclasses.py, optree/ops.py, optree/registry.py, optree/typing.py, optree/utils.py, pyproject.toml, src/treespec/gc.cpp
=> deps!(python): drop Python 3.8 support

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/tests.yml, CHANGELOG.md, CMakeLists.txt, Makefile, conda-recipe.yaml, include/optree/treespec.h, optree/_C.pyi, pyproject.toml, src/optree.cpp, tests/requirements.txt, tests/test_ops.py
=> feat: dump build-time meta-information to C extension

.gitattributes, .gitignore, .pre-commit-config.yaml, CMakeLists.txt, include/optree/exceptions.h, src/optree.cpp, tests/test_treespec.py, tests/test_typing.py, tests/test_utils.py
=> test(treespec): add tests for `PyTreeSpec.{__new__,__init__}`

CHANGELOG.md, pyproject.toml
=> deps!(setuptools): migrate to `setuptools>=77` for PEP-639

.github/workflows/tests-with-pydebug.yml, .pre-commit-config.yaml, optree/_C.pyi, src/CMakeLists.txt, src/optree.cpp, tests/.coveragerc, tests/confcoverage.py, tests/helpers.py, tests/test_concurrent.py, tests/test_functools.py, tests/test_ops.py, tests/test_registry.py, tests/test_treespec.py, tests/test_typing.py
See also:
- python/cpython#134216
=> test: handle trace function change for `coverage`

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, .pre-commit-config.yaml
=> feat(workflows): save `pip` and `pre-commit` caches in CI

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, CHANGELOG.md, include/optree/treespec.h, optree/__init__.py, optree/ops.py, tests/conftest.py, tests/helpers.py, tests/test_accessors.py, tests/test_concurrent.py, tests/test_ops.py, tests/test_treespec.py
=> feat: add WASM support

.github/workflows/lint.yml, .github/workflows/tests-with-pydebug.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, CHANGELOG.md
=> deps(pybind11): build wheels against `pybind11` 3.0.0

.github/workflows/build.yml, CHANGELOG.md, optree/version.py, pyproject.toml, setup.py, tests/helpers.py, tests/test_accessors.py, tests/test_ops.py, tests/test_treespec.py
=> feat: add iOS support

.github/workflows/build.yml, .pre-commit-config.yaml, CHANGELOG.md, pyproject.toml
=> feat(workflows): use ARM-based GHA runners to build ARM wheels

.github/workflows/build.yml, CHANGELOG.md, pyproject.toml, setup.py
=> feat(workflows/build): add `cp314-ios` / `cp313-pyodide` wheels
